#pragma once
#define TO_STR_IMPL(x) #x
#define TO_STR(x) TO_STR_IMPL(x)
#define TO_WSTR_IMPL(x) L ## #x
#define TO_WSTR(x) TO_WSTR_IMPL(x)
#define STR_TO_WSTR_IMPL(x) L ## x
#define STR_TO_WSTR(x) STR_TO_WSTR_IMPL(x)

#define PRODUCT_VERSION_MAJOR 0
#define PRODUCT_VERSION_MINOR 0
#define PRODUCT_VERSION_RELEASE 0

#define PRODUCT_VERSION (PRODUCT_VERSION_MAJOR*10000+PRODUCT_VERSION_MINOR*100+PRODUCT_VERSION_RELEASE)
#define PRODUCT_LOWEST_SUPPORTED_VERSION 0

#define PRODUCT_VERSION_MAJOR_STR TO_STR(PRODUCT_VERSION_MAJOR)
#define PRODUCT_VERSION_MINOR_STR TO_STR(PRODUCT_VERSION_MINOR)
#define PRODUCT_VERSION_RELEASE_STR TO_STR(PRODUCT_VERSION_RELEASE)
#define PRODUCT_VERSION_STR PRODUCT_VERSION_MAJOR_STR "." PRODUCT_VERSION_MINOR_STR "." PRODUCT_VERSION_RELEASE_STR

#define PRODUCT_VERSION_MAJOR_WSTR TO_WSTR(PRODUCT_VERSION_MAJOR)
#define PRODUCT_VERSION_MINOR_WSTR TO_WSTR(PRODUCT_VERSION_MINOR)
#define PRODUCT_VERSION_RELEASE_WSTR TO_WSTR(PRODUCT_VERSION_RELEASE)
#define PRODUCT_VERSION_WSTR PRODUCT_VERSION_MAJOR_WSTR L"." PRODUCT_VERSION_MINOR_WSTR L"." PRODUCT_VERSION_RELEASE_WSTR

#define PRODUCT_LIBNAME_STR "IHIProj"
#define PRODUCT_LIBRARY_STR "IHIProj.dll"
#define PRODUCT_SERIES_STR "IH Extension"

#define PRODUCT_LIBNAME_WSTR STR_TO_WSTR(PRODUCT_LIBNAME_STR)
#define PRODUCT_LIBRARY_WSTR STR_TO_WSTR(PRODUCT_LIBRARY_STR)
#define PRODUCT_SERIES_WSTR STR_TO_WSTR(PRODUCT_SERIES_STR)

#define FILE_VERSION PRODUCT_VERSION
#define FILE_VERSION_STR PRODUCT_VERSION_STR

#define PRODUCT_VERSION_RC PRODUCT_VERSION_MAJOR,PRODUCT_VERSION_MINOR,PRODUCT_VERSION_RELEASE,0
#define FILE_VERSION_RC PRODUCT_VERSION_MAJOR,PRODUCT_VERSION_MINOR,PRODUCT_VERSION_RELEASE,0

#ifdef CUSTOM_VERSION_STR
#define PRODUCT_FULLNAME_STR PRODUCT_SERIES_STR " " PRODUCT_LIBRARY_STR " " CUSTOM_VERSION_STR
#define PRODUCT_FULLNAME_WSTR PRODUCT_SERIES_WSTR L" " PRODUCT_LIBRARY_WSTR L" " CUSTOM_VERSION_STR
#define PRODUCT_FULLNAME_U8STR u8"" PRODUCT_SERIES_STR " " PRODUCT_LIBRARY_STR " " CUSTOM_VERSION_STR
#define FINAL_VERSION_STR CUSTOM_VERSION_STR
#else
#define PRODUCT_FULLNAME_STR PRODUCT_SERIES_STR " " PRODUCT_LIBRARY_STR " " PRODUCT_VERSION_STR
#define PRODUCT_FULLNAME_WSTR PRODUCT_SERIES_WSTR L" " PRODUCT_LIBRARY_WSTR L" " PRODUCT_VERSION_WSTR
#define PRODUCT_FULLNAME_U8STR u8"" PRODUCT_SERIES_STR " " PRODUCT_LIBRARY_STR " " PRODUCT_VERSION_STR
#define FINAL_VERSION_STR PRODUCT_VERSION_STR
#endif
